version: "3.7"
services:
  mariadb:
    image: docker.io/mariadb:10.6
    platform: linux/amd64
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  fxmed:
    image: fxgroup/frappe-nginx:latest
    environment:
      - FRAPPE_SITE_NAME_HEADER=fxmed.local
      - BACKEND=backend:8000
      - SOCKETIO=websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8081:8080"

  naturalmeds:
    image: fxgroup/frappe-nginx:latest
    environment:
      - FRAPPE_SITE_NAME_HEADER=naturalmeds.local
      - BACKEND=backend:8000
      - SOCKETIO=websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8082:8080"

  rnlabs:
    image: fxgroup/frappe-nginx:latest
    environment:
      - FRAPPE_SITE_NAME_HEADER=rnlabs.local
      - BACKEND=backend:8000
      - SOCKETIO=websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8083:8080"

  therahealth:
    image: fxgroup/frappe-nginx:latest
    environment:
      - FRAPPE_SITE_NAME_HEADER=therahealth.local
      - BACKEND=backend:8000
      - SOCKETIO=websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    ports:
      - "8084:8080"

  redis-cache:
    image: docker.io/redis:alpine
    platform: linux/amd64

  redis-queue:
    image: docker.io/redis:alpine
    platform: linux/amd64

  frappe:
    image: docker.io/frappe/bench:latest
    platform: linux/amd64
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace:cached
      # Enable if you require git cloning
      # - ${HOME}/.ssh:/home/frappe/.ssh
    working_dir: /workspace/development
    ports:
      - 8000-8005:8000-8005
      - 9000-9005:9000-9005
 
volumes:
  mariadb-data:
  #postgresql-data:
  #mailpit-data:
