x-customizable-image: &customizable_image
  # By default the image used only contains the `frappe` and `erpnext` apps.
  # See https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
  # about using custom images.
  image: ${CUSTOM_IMAGE:-fxgroup/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
  pull_policy: ${PULL_POLICY:-always}
  restart: ${RESTART_POLICY:-unless-stopped}

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: *customizable_image
  volumes:
    - sites:/home/frappe/frappe-bench/sites

services:
  configurator:
    <<: *backend_defaults
    platform: linux/amd64

    # Mount our bootstrap script and custom-apps file
    volumes:
      - ${PWD}/overrides/bootstrap.sh:/assets/bootstrap.sh:ro
      - ${PWD}/overrides/apps.json:/assets/apps.json:ro
      - ${PWD}/overrides/custom-apps.txt:/assets/custom-apps.txt:ro
      - sites:/home/frappe/frappe-bench/sites

    # Run bash on our script
    entrypoint: ["bash", "/assets/bootstrap.sh"]

    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - REDIS_CACHE=${REDIS_CACHE:-redis:6379}
      - REDIS_QUEUE=${REDIS_QUEUE:-redis:6379}
      - SOCKETIO_PORT=${SOCKETIO_PORT:-9000}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin123}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}

    restart: "no"

    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy

  backend:
    <<: [*backend_defaults, *depends_on_configurator]
    platform: linux/amd64

  fxmed-frontend:
    <<: *customizable_image
    platform: linux/amd64
    command:
     - nginx-entrypoint.sh
    environment:
     BACKEND: backend:8000
     SOCKETIO: websocket:9000
     FRAPPE_SITE_NAME_HEADER: fxmed.local
     UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
     UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
     UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
     PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
     CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
     - sites:/home/frappe/frappe-bench/sites
    ports:
     - "8081:8080"
    depends_on:
     - backend
     - websocket

  naturalmeds-frontend:
    <<: *customizable_image
    platform: linux/amd64
    command:
     - nginx-entrypoint.sh
    environment:
     BACKEND: backend:8000
     SOCKETIO: websocket:9000
     FRAPPE_SITE_NAME_HEADER: naturalmeds.local
     UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
     UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
     UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
     PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
     CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
     - sites:/home/frappe/frappe-bench/sites
    ports:
     - "8082:8080"
    depends_on:
     - backend
     - websocket

  rnlabs-frontend:
    <<: *customizable_image
    platform: linux/amd64
    command:
     - nginx-entrypoint.sh
    environment:
     BACKEND: backend:8000
     SOCKETIO: websocket:9000
     FRAPPE_SITE_NAME_HEADER: rnlabs.local
     UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
     UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
     UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
     PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
     CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
     - sites:/home/frappe/frappe-bench/sites
    ports:
     - "8083:8080"
    depends_on:
     - backend
     - websocket

  therahealth-frontend:
    <<: *customizable_image
    platform: linux/amd64
    command:
     - nginx-entrypoint.sh
    environment:
     BACKEND: backend:8000
     SOCKETIO: websocket:9000
     FRAPPE_SITE_NAME_HEADER: therahealth.local
     UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
     UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
     UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
     PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
     CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
     - sites:/home/frappe/frappe-bench/sites
    ports:
     - "8084:8080"
    depends_on:
     - backend
     - websocket

  websocket:
    <<: [*depends_on_configurator, *customizable_image]
    platform: linux/amd64
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  queue-short:
    <<: [*backend_defaults, *depends_on_configurator]
    platform: linux/amd64
    command: bench worker --queue short,default

  queue-long:
    <<: [*backend_defaults, *depends_on_configurator]
    platform: linux/amd64
    command: bench worker --queue long,default,short

  scheduler:
    <<: [*backend_defaults, *depends_on_configurator]
    platform: linux/amd64
    command: bench schedule

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "frappe"
      MYSQL_USER: "frappe"
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7.0-alpine
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - redis-cache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-queue:
    image: redis:7.0-alpine
    command: redis-server --save 900 1 --loglevel warning
    volumes:
      - redis-queue-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
# ERPNext requires local assets access (Frappe does not)
volumes:
  sites:
  mariadb_data:
  redis-cache-data:
  redis-queue-data: